export default class ExchangeRateService {
  static getExchangeRate(amountUSD, globalCurrency) {
    return fetch(`https://v6.exchangerate-api.com/v6/${process.env.API_KEY}/pair/USD/${userInput}`)
      .then(function(response) {
        if (!response.ok) {
          const errorMessage = `${response.result} ${response[error-type]}`;
          throw new Error(errorMessage);
        } else {
          return response.json();
        }
      })
      .catch(function(error) {
        return error;
      });
  }
}

export default class CountryCurrencyList {
  [
    {"cc":"AED","symbol":"د.إ;","name":"UAE Dirham"},
    {"cc":"AFN","symbol":"؋","name":"Afghan Afghani"},
    {"cc":"ALL","symbol":"Lek","name":"Albanian Lek"},
    {"cc":"AMD","symbol":"֏","name":"Armenian Dram"},
    {"cc":"ANG","symbol":"ƒ","name":"Netherlands Antillean Guilder"},
    {"cc":"AOA","symbol":"Kz","name":"Angolan Kwanza"},
    {"cc":"ARS","symbol":"$","name":"Argentine Peso"},
    {"cc":"AUD","symbol":"$","name":"Australian Dollar"},
    {"cc":"AWG","symbol":"ƒ","name":"Aruban Florin"},
    {"cc":"AZN","symbol":"₼","name":"Azerbaijani Manat"},
    {"cc":"BAM","symbol":"KM","name":"Bosnia and Herzegovina Mark"},
    {"cc":"BBD","symbol":"$","name":"Barbados Dollar"},
    {"cc":"BDT","symbol":"৳","name":"Bangladeshi Taka"},
    {"cc":"BGN","symbol":"лв","name":"Bulgarian Lev"},
    {"cc":"BHD","symbol":"د.ب","name":"Bahraini Dinar"},
    {"cc":"BIF","symbol":"FBu/₣","name":"Burundian Franc"},
    {"cc":"BMD","symbol":"$","name":"Bermudian Dollar"},
    {"cc":"BND","symbol":"$","name":"Brunei Dollar"},
    {"cc":"BOB","symbol":"$b","name":"Bolivian Boliviano"},
    {"cc":"BRL","symbol":"R$","name":"Brazilian Real"},
    {"cc":"BSD","symbol":"$","name":"Bahamian Dollar"},
    {"cc":"BTN","symbol":"Nu.","name":"Bhutanese Ngultrum"},
    {"cc":"BWP","symbol":"P","name":"Botswana Pula"},
    {"cc":"BYR","symbol":"Br","name":"Belarusian Ruble"},
    {"cc":"BZD","symbol":"BZ$","name":"Belize Dollar"},
    {"cc":"CAD","symbol":"$","name":"Canadian Dollar"},
    {"cc":"CDF","symbol":"C₣","name":"Congolese Franc"},
    {"cc":"CHF","symbol":"CHF/₣","name":"Swiss Franc"},
    {"cc":"CLP","symbol":"$","name":"Chilean Peso"},
    {"cc":"CNY","symbol":"¥","name":"Chinese Renminbi"},
    {"cc":"COP","symbol":"$","name":"Colombian Peso"},
    {"cc":"CRC","symbol":"₡","name":"Costa Rican Colon"},
    {"cc":"CUC","symbol":"₱","name":"Cuban Peso"},
    {"cc":"CVE","symbol":"Esc$","name":"Cape Verdean Escudo"},
    {"cc":"CZK","symbol":"Kč","name":"Czech Koruna"},
    {"cc":"DJF","symbol":"Fdj/₣","name":"Djiboutian Franc"},
    {"cc":"DKK","symbol":"kr","name":"Danish Krone"},
    {"cc":"DOP","symbol":"RD$","name":"Dominican Peso"},
    {"cc":"DZD","symbol":"دج","name":"Algerian Dinar"},
    {"cc":"EGP","symbol":"£","name":"Egyptian Pound"},
    {"cc":"ERN","symbol":"Nkf/ናቕፋ","name":"Eritrean Nakfa"},
    {"cc":"ETB","symbol":"ብር","name":"Ethiopian Birr"},
    {"cc":"EUR","symbol":"€","name":"Euro"},
    {"cc":"FJD","symbol":"FJ$","name":"Fiji Dollar"},
    {"cc":"FKP","symbol":"£","name":"Falkland Islands Pound"},
    {"cc":"GBP","symbol":"£","name":"Pound Sterling"},
    {"cc":"GEL","symbol":"ლ","name":"Georgian Lari"},
    {"cc":"GHS","symbol":"¢","name":"Ghanaian Cedi"},
    {"cc":"GIP","symbol":"£","name":"Gibraltar Pound"},
    {"cc":"GMD","symbol":"D","name":"Gambian Dalasi"},
    {"cc":"GNF","symbol":"FG","name":"Guinean Franc"},
    {"cc":"GTQ","symbol":"Q","name":"Guatemalan Quetzal"},
    {"cc":"GYD","symbol":"GY$","name":"Guyanese Dollar"},
    {"cc":"HKD","symbol":"HK$","name":"Hong Kong Dollar"},
    {"cc":"HNL","symbol":"L","name":"Honduran Lempira"},
    {"cc":"HRK","symbol":"kn","name":"Croatian Kuna"},
    {"cc":"HTG","symbol":"G","name":"Haitian Gourde"},
    {"cc":"HUF","symbol":"Ft","name":"Hungarian Forint"},
    {"cc":"IDR","symbol":"Rp","name":"Indonesian Rupiah"},
    {"cc":"ILS","symbol":"₪","name":"Israeli Shekel"},
    {"cc":"IMP", "symbol":"£","name":"Manx Pound"},
    {"cc":"INR","symbol":"₹","name":"Indian Rupee"},
    {"cc":"IQD","symbol":"ع.د","name":"Iraqi Dinar"},
    {"cc":"IRR","symbol":"﷼","name":"Iranian Rial"},
    {"cc":"ISK","symbol":"kr","name":"Icelandic Króna"},
    {"cc":"JEP","symbol":"£","name":"Jersey Pound"},
    {"cc":"JMD","symbol":"J$","name":"Jamaican Dollar"},
    {"cc":"JOD","symbol":"د.ا","name":"Jordanian Dinar"},
    {"cc":"JPY","symbol":"¥","name":"Japanese Yen"},
    {"cc":"KES","symbol":"Ksh","name":"Kenyan Shilling"},
    {"cc":"KGS","symbol":"лв","name":"Kyrgyzstani Som"},
    {"cc":"KHR","symbol":"៛","name":"Cambodian Riel"},
    {"cc":"KID","symbol":"$","name":"Kiribati Dollar"},
    {"cc":"KMF","symbol":"CF/₣","name":"Comorian Franc"},
    {"cc":"KRW","symbol":"₩","name":"South Korean Won"},
    {"cc":"KWD","symbol":"د.ك","name":"Kuwaiti Dinar"},
    {"cc":"KYD","symbol":"$","name":"Cayman Islands Dollar"},
    {"cc":"KZT","symbol":"лв","name":"Kazakhstani Tenge"},
    {"cc":"LAK","symbol":"₭","name":"Lao Kip"},
    {"cc":"LBP","symbol":"£","name":"Lebanese Pound"},
    {"cc":"LKR","symbol":"Rs/₹","name":"Sri Lankan Rupee"},
    {"cc":"LRD","symbol":"$","name":"Liberian Dollar"},
    {"cc":"LSL","symbol":"L/M","name":"Lesotho Loti"},
    {"cc":"LYD","symbol":"ل.د","name":"Libyan Dinar"},
    {"cc":"MAD","symbol":"د.إ","name":"Moroccan Dirham"},
    {"cc":"MDL","symbol":"L","name":"Moldovan Leu"},
    {"cc":"MGA","symbol":"Ar","name":"Malagasy Ariary"},
    {"cc":"MKD","symbol":"ден","name":"Macedonian Denar"},
    {"cc":"MMK","symbol":"K","name":"Burmese Kyat"},
    {"cc":"MNT","symbol":"₮","name":"Mongolian Tögrög"},
    {"cc":"MOP","symbol":"$","name":"Macanese Pataca"},
    {"cc":"MRO","symbol":"UM","name":"Mauritanian Ouguiya"},
    {"cc":"MUR","symbol":"Rs","name":"Mauritian Rupee"},
    {"cc":"MVR","symbol":"Rf/.ރ","name":"Maldivian Rufiyaa"},
    {"cc":"MWK","symbol":"MK","name":"Malawian Kwacha"},
    {"cc":"MXN","symbol":"$","name":"Mexican Peso"},
    {"cc":"MYR","symbol":"RM","name":"Malaysian Ringgit"},
    {"cc":"MZM","symbol":"MT","name":"Mozambican Metical"},
    {"cc":"NAD","symbol":"N$","name":"Namibian Dollar"},
    {"cc":"NGN","symbol":"₦","name":"Nigerian Naira"},
    {"cc":"NIO","symbol":"C$","name":"Nicaraguan Córdoba"},
    {"cc":"NOK","symbol":"kr","name":"Norwegian Krone"},
    {"cc":"NPR","symbol":"Rs","name":"Nepalese Rupee"},
    {"cc":"NZD","symbol":"NZ$","name":"New Zealand Dollar"},
    {"cc":"OMR","symbol":"﷼","name":"Omani Rial"},
    {"cc":"PAB","symbol":"B/.","name":"Panamanian Balboa"},
    {"cc":"PEN","symbol":"S/.","name":"Peruvian Sol"},
    {"cc":"PGK","symbol":"K","name":"Papua New Guinean Kina"},
    {"cc":"PHP","symbol":"₱","name":"Philippine Peso"},
    {"cc":"PKR","symbol":"Rs","name":"Pakistani Rupee"},
    {"cc":"PLN","symbol":"zł","name":"Polish Zloty"},
    {"cc":"PYG","symbol":"Gs","name":"Paraguayan Guarani"},
    {"cc":"QAR","symbol":"﷼","name":"Qatari Riyal"},
    {"cc":"RON","symbol":"lei","name":"Romanian Leu"},
    {"cc":"RSD","symbol":"Дин.","name":"Serbian Dinar"},
    {"cc":"RUB","symbol":"₽","name":"Russian Ruble"},
    {"cc":"RWF","symbol":"RWF/₣","name":"Rwandan Franc"},
    {"cc":"SAR","symbol":"﷼","name":"Saudi Riyal"},
    {"cc":"SBD","symbol":"SI$","name":"Solomon Islands Dollar"},
    {"cc":"SCR","symbol":"Rs","name":"Seychellois Rupee"},
    {"cc":"SDG","symbol":"£","name":"Sudanese Pound"},
    {"cc":"SEK","symbol":"kr","name":"Swedish Krona"},
    {"cc":"SGD","symbol":"$","name":"Singapore Dollar"},
    {"cc":"SHP","symbol":"£","name":"Saint Helena Pound"},
    {"cc":"SLL","symbol":"Le","name":"Sierra Leonean Leone"},
    {"cc":"SOS","symbol":"S","name":"Somali Shilling"},
    {"cc":"SRD","symbol":"$","name":"Surinamese Dollar"},
    {"cc":"SSP","symbol":"£","name":"South Sudanese Pound"},
    {"cc":"STN","symbol":"Db","name":"São Tomé and Príncipe Dobra"},
    {"cc":"SYP","symbol":"£","name":"Syrian Pound"},
    {"cc":"SZL","symbol":"E","name":"Eswatini Lilangeni"},
    {"cc":"THB","symbol":"฿","name":"Thai Baht"},
    {"cc":"TJS","symbol":"SM","name":"Tajikistani Somoni"},
    {"cc":"TMT","symbol":"T","name":"Turkmen Manat"},
    {"cc":"TND","symbol":"د.ت","name":"Tunisian Dinar"},
    {"cc":"TRY","symbol":"₺","name":"Turkish Lira"},
    {"cc":"TTD","symbol":"TT$","name":"Trinidad and Tobago Dollar"},
    {"cc":"TWD","symbol":"NT$","name":"New Taiwan Dollar"},
    {"cc":"TZS","symbol":"TSh","name":"Tanzanian Shilling"},
    {"cc":"UAH","symbol":"₴","name":"Ukrainian Hryvnia"},
    {"cc":"UGX","symbol":"USh","name":"Ugandan Shilling"},
    {"cc":"USD","symbol":"US$","name":"United States Dollar"},
    {"cc":"UYU","symbol":"$U","name":"Uruguayan Peso"},
    {"cc":"UZS","symbol":"лв","name":"Uzbekistani So'm"},
    {"cc":"VES","symbol":"Bs","name":"Venezuelan Bolivar Soberano"},
    {"cc":"VND","symbol":"₫","name":"Vietnamese Đồng"},
    {"cc":"VUV","symbol":"VT","name":"Vanuatu Vatu"},
    {"cc":"WST","symbol":"WS$","name":"Samoan Tālā"},
    {"cc":"XAF","symbol":"CFA/₣","name":"Central African CFA Franc"},
    {"cc":"XCD","symbol":"EC$","name":"East Caribbean Dollar"},
    {"cc":"XDR","symbol":"SDR","name":"Special Drawing Rights"},
    {"cc":"XOF","symbol":"CFA/₣","name":"West African CFA Franc"},
    {"cc":"XPF","symbol":"F/₣","name":"CFP Franc"},
    {"cc":"YER","symbol":"﷼","name":"Yemeni Rial"},
    {"cc":"ZAR","symbol":"R","name":"South African Rand"},
    {"cc":"ZMK","symbol":"ZK","name":"Zambian Kwacha"},
    {"cc":"ZWR","symbol":"Z$","name":"Zimbabwean Dollar"}
  ]
}