export default class ExchangeRateService {
  static getExchangeRate(amountUSD, globalCurrency) {
    return fetch(`https://v6.exchangerate-api.com/v6/${process.env.API_KEY}/pair/USD/${userInput}`)
      .then(function(response) {
        if (!response.ok) {
          const errorMessage = `${response.result} ${response[error-type]}`;
          throw new Error(errorMessage);
        } else {
          return response.json();
        }
      })
      .catch(function(error) {
        return error;
      });
  }
}

export default class CountryCurrencyList {
  [
    {"cc":"AED","symbol":"د.إ;","name":"UAE Dirham"},
    {"cc":"AFN","symbol":"؋","name":"Afghan Afghani"},
    {"cc":"ALL","symbol":"Lek","name":"Albanian Lek"},
    {"cc":"AMD","symbol":"֏","name":"Armenian Dram"},
    {"cc":"ANG","symbol":"NA\u0192","name":"Netherlands Antillean Guilder"},
    {"cc":"AOA","symbol":"Kz","name":"Angolan Kwanza"},
    {"cc":"ARS","symbol":"$","name":"Argentine Peso"},
    {"cc":"AUD","symbol":"$","name":"Australian Dollar"},
    {"cc":"AWG","symbol":"\u0192","name":"Aruban Florin"},
    {"cc":"AZN","symbol":"AZN","name":"Azerbaijani Manat"},
    {"cc":"BAM","symbol":"KM","name":"Bosnia and Herzegovina Mark"},
    {"cc":"BBD","symbol":"Bds$","name":"Barbados Dollar"},
    {"cc":"BDT","symbol":"\u09f3","name":"Bangladeshi Taka"},
    {"cc":"BGN","symbol":"BGN","name":"Bulgarian Lev"},
    {"cc":"BHD","symbol":".\u062f.\u0628","name":"Bahraini Dinar"},
    {"cc":"BIF","symbol":"FBu","name":"Burundian Franc"},
    {"cc":"BMD","symbol":"BD$","name":"Bermudian Dollar"},
    {"cc":"BND","symbol":"B$","name":"Brunei Dollar"},
    {"cc":"BOB","symbol":"Bs.","name":"Bolivian Boliviano"},
    {"cc":"BRL","symbol":"R$","name":"Brazilian Real"},
    {"cc":"BSD","symbol":"B$","name":"Bahamian Dollar"},
    {"cc":"BTN","symbol":"Nu.","name":"Bhutanese Ngultrum"},
    {"cc":"BWP","symbol":"P","name":"Botswana Pula"},
    {"cc":"BYR","symbol":"Br","name":"Belarusian Ruble"},
    {"cc":"BZD","symbol":"BZ$","name":"Belize Dollar"},
    {"cc":"CAD","symbol":"$","name":"Canadian Dollar"},
    {"cc":"CDF","symbol":"F","name":"Congolese Franc"},
    {"cc":"CHF","symbol":"Fr.","name":"Swiss Franc"},
    {"cc":"CLP","symbol":"$","name":"Chilean Peso"},
    {"cc":"CNY","symbol":"\u00a5","name":"Chinese Renminbi"},
    {"cc":"COP","symbol":"Col$","name":"Colombian Peso"},
    {"cc":"CRC","symbol":"\u20a1","name":"Costa Rican Colon"},
    {"cc":"CUC","symbol":"$","name":"Cuban Peso"},
    {"cc":"CVE","symbol":"Esc","name":"Cape Verdean Escudo"},
    {"cc":"CZK","symbol":"K\u010d","name":"Czech Koruna"},
    {"cc":"DJF","symbol":"Fdj","name":"Djiboutian Franc"},
    {"cc":"DKK","symbol":"Kr","name":"Danish Krone"},
    {"cc":"DOP","symbol":"RD$","name":"Dominican Peso"},
    {"cc":"DZD","symbol":"\u062f.\u062c","name":"Algerian Dinar"},
    {"cc":"EGP","symbol":"\u00a3","name":"Egyptian Pound"},
    {"cc":"ERN","symbol":"Nfa","name":"Eritrean Nakfa"},
    {"cc":"ETB","symbol":"Br","name":"Ethiopian Birr"},
    {"cc":"EUR","symbol":"\u20ac","name":"Euro"},
    {"cc":"FJD","symbol":"FJ$","name":"Fiji Dollar"},
    {"cc":"FKP","symbol":"\u00a3","name":"Falkland Islands Pound"},
    {"cc":"GBP","symbol":"\u00a3","name":"Pound Sterling"},
    {"cc":"GEL","symbol":"GEL","name":"Georgian Lari"},
    {"cc":"GHS","symbol":"GH\u20b5","name":"Ghanaian Cedi"},
    {"cc":"GIP","symbol":"\u00a3","name":"Gibraltar Pound"},
    {"cc":"GMD","symbol":"D","name":"Gambian Dalasi"},
    {"cc":"GNF","symbol":"FG","name":"Guinean Franc"},
    {"cc":"GTQ","symbol":"Q","name":"Guatemalan Quetzal"},
    {"cc":"GYD","symbol":"GY$","name":"Guyanese Dollar"},
    {"cc":"HKD","symbol":"HK$","name":"Hong Kong Dollar"},
    {"cc":"HNL","symbol":"L","name":"Honduran Lempira"},
    {"cc":"HRK","symbol":"kn","name":"Croatian Kuna"},
    {"cc":"HTG","symbol":"G","name":"Haitian Gourde"},
    {"cc":"HUF","symbol":"Ft","name":"Hungarian Forint"},
    {"cc":"IDR","symbol":"Rp","name":"Indonesian Rupiah"},
    {"cc":"ILS","symbol":"\u20aa","name":"Israeli New Shekel"},
    {"cc":"IMP", "symbol":"£","name":"Manx Pound"},
    {"cc":"INR","symbol":"\u20B9","name":"Indian Rupee"},
    {"cc":"IQD","symbol":"\u062f.\u0639","name":"Iraqi Dinar"},
    {"cc":"IRR","symbol":"IRR","name":"Iranian Rial"},
    {"cc":"ISK","symbol":"kr","name":"Icelandic Króna"},
    {"cc":"JEP","symbol":"jp","name":"Jersey Pound"},
    {"cc":"JMD","symbol":"J$","name":"Jamaican Dollar"},
    {"cc":"JOD","symbol":"JOD","name":"Jordanian Dinar"},
    {"cc":"JPY","symbol":"\u00a5","name":"Japanese Yen"},
    {"cc":"KES","symbol":"KSh","name":"Kenyan Shilling"},
    {"cc":"KGS","symbol":"\u0441\u043e\u043c","name":"Kyrgyzstani Som"},
    {"cc":"KHR","symbol":"\u17db","name":"Cambodian Riel"},
    {"cc":"KID","symbol":"ki","name":"Kiribati Dollar"},
    {"cc":"KMF","symbol":"KMF","name":"Comorian Franc"},
    {"cc":"KRW","symbol":"W","name":"South Korean Won"},
    {"cc":"KWD","symbol":"KWD","name":"Kuwaiti Dinar"},
    {"cc":"KYD","symbol":"KY$","name":"Cayman Islands Dollar"},
    {"cc":"KZT","symbol":"T","name":"Kazakhstani Tenge"},
    {"cc":"LAK","symbol":"KN","name":"Lao Kip"},
    {"cc":"LBP","symbol":"\u00a3","name":"Lebanese Pound"},
    {"cc":"LKR","symbol":"Rs","name":"Sri Lankan Rupee"},
    {"cc":"LRD","symbol":"L$","name":"Liberian Dollar"},
    {"cc":"LSL","symbol":"M","name":"Lesotho Loti"},
    {"cc":"LYD","symbol":"LD","name":"Libyan Dinar"},
    {"cc":"MAD","symbol":"MAD","name":"Moroccan Dirham"},
    {"cc":"MDL","symbol":"MDL","name":"Moldovan Leu"},
    {"cc":"MGA","symbol":"FMG","name":"Malagasy Ariary"},
    {"cc":"MKD","symbol":"MKD","name":"Macedonian Denar"},
    {"cc":"MMK","symbol":"K","name":"Burmese Kyat"},
    {"cc":"MNT","symbol":"\u20ae","name":"Mongolian Tögrög"},
    {"cc":"MOP","symbol":"P","name":"Macanese Pataca"},
    {"cc":"MRO","symbol":"UM","name":"Mauritanian Ouguiya"},
    {"cc":"MUR","symbol":"Rs","name":"Mauritian Rupee"},
    {"cc":"MVR","symbol":"Rf","name":"Maldivian Rufiyaa"},
    {"cc":"MWK","symbol":"MK","name":"Malawian Kwacha"},
    {"cc":"MXN","symbol":"$","name":"Mexican Peso"},
    {"cc":"MYR","symbol":"RM","name":"Malaysian Ringgit"},
    {"cc":"MZM","symbol":"MTn","name":"Mozambican Metical"},
    {"cc":"NAD","symbol":"N$","name":"Namibian Dollar"},
    {"cc":"NGN","symbol":"\u20a6","name":"Nigerian Naira"},
    {"cc":"NIO","symbol":"C$","name":"Nicaraguan Córdoba"},
    {"cc":"NOK","symbol":"kr","name":"Norwegian Krone"},
    {"cc":"NPR","symbol":"NRs","name":"Nepalese Rupee"},
    {"cc":"NZD","symbol":"NZ$","name":"New Zealand Dollar"},
    {"cc":"OMR","symbol":"OMR","name":"Omani Rial"},
    {"cc":"PAB","symbol":"B./","name":"Panamanian Balboa"},
    {"cc":"PEN","symbol":"S/.","name":"Peruvian Sol"},
    {"cc":"PGK","symbol":"K","name":"Papua New Guinean Kina"},
    {"cc":"PHP","symbol":"\u20b1","name":"Philippine Peso"},
    {"cc":"PKR","symbol":"Rs.","name":"Pakistani Rupee"},
    {"cc":"PLN","symbol":"z\u0142","name":"Polish Zloty"},
    {"cc":"PYG","symbol":"\u20b2","name":"Paraguayan Guarani"},
    {"cc":"QAR","symbol":"QR","name":"Qatari Riyal"},
    {"cc":"RON","symbol":"L","name":"Romanian Leu"},
    {"cc":"RSD","symbol":"din.","name":"Serbian Dinar"},
    {"cc":"RUB","symbol":"R","name":"Russian Ruble"},
    {"cc":"RWF","symbol":"Fr","name":"Rwandan Franc"},
    {"cc":"SAR","symbol":"SR","name":"Saudi Riyal"},
    {"cc":"SBD","symbol":"SI$","name":"Solomon Islands Dollar"},
    {"cc":"SCR","symbol":"SR","name":"Seychellois Rupee"},
    {"cc":"SDG","symbol":"SDG","name":"Sudanese Pound"},
    {"cc":"SEK","symbol":"kr","name":"Swedish Krona"},
    {"cc":"SGD","symbol":"S$","name":"Singapore Dollar"},
    {"cc":"SHP","symbol":"£","name":"Saint Helena Pound"},
    {"cc":"SLL","symbol":"Le","name":"Sierra Leonean Leone"},
    {"cc":"SOS","symbol":"Sh.","name":"Somali Shilling"},
    {"cc":"SRD","symbol":"$","name":"Surinamese Dollar"},
    {"cc":"SSP","symbol":"£","name":"South Sudanese Pound"},
    {"cc":"STN","symbol":"Db","name":"São Tomé and Príncipe Dobra"},
    {"cc":"SYP","symbol":"£","name":"Syrian Pound"},
    {"cc":"SZL","symbol":"E","name":"Eswatini Lilangeni"},
    {"cc":"THB","symbol":"\u0e3f","name":"Thai Baht"},
    {"cc":"TJS","symbol":"TJS","name":"Tajikistani Somoni"},
    {"cc":"TMT","symbol":"m","name":"Turkmen Manat"},
    {"cc":"TND","symbol":"DT","name":"Tunisian Dinar"},
    {"cc":"TRY","symbol":"TRY","name":"Turkish Lira"},
    {"cc":"TTD","symbol":"TT$","name":"Trinidad and Tobago Dollar"},
    {"cc":"TWD","symbol":"NT$","name":"New Taiwan Dollar"},
    {"cc":"TZS","symbol":"TZS","name":"Tanzanian Shilling"},
    {"cc":"UAH","symbol":"UAH","name":"Ukrainian Hryvnia"},
    {"cc":"UGX","symbol":"USh","name":"Ugandan Shilling"},
    {"cc":"USD","symbol":"US$","name":"United States Dollar"},
    {"cc":"UYU","symbol":"$U","name":"Uruguayan Peso"},
    {"cc":"UZS","symbol":"UZS","name":"Uzbekistani So'm"},
    {"cc":"VES","symbol":"Bs","name":"Venezuelan Bolivar Soberano"},
    {"cc":"VND","symbol":"\u20ab","name":"Vietnamese Đồng"},
    {"cc":"VUV","symbol":"VT","name":"Vanuatu Vatu"},
    {"cc":"WST","symbol":"WS$","name":"Samoan Tālā"},
    {"cc":"XAF","symbol":"CFA","name":"Central African CFA Franc"},
    {"cc":"XCD","symbol":"EC$","name":"East Caribbean Dollar"},
    {"cc":"XDR","symbol":"SDR","name":"Special Drawing Rights"},
    {"cc":"XOF","symbol":"CFA","name":"West African CFA Franc"},
    {"cc":"XPF","symbol":"F","name":"CFP Franc"},
    {"cc":"YER","symbol":"YER","name":"Yemeni Rial"},
    {"cc":"ZAR","symbol":"R","name":"South African Rand"},
    {"cc":"ZMK","symbol":"ZK","name":"Zambian Kwacha"},
    {"cc":"ZWR","symbol":"Z$","name":"Zimbabwean Dollar"}
  ]
}